on: 
    push:
        branches:
            - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: "162.240.146.206"
        username: "painelresi"
        password: "fPAUkwR6Y=E(lZ&w,4"
        server-dir: "public_html/"
  